### ISSUE TITLE
Unclear Readme

### ISSUE THREAD

**Issue by mablae** [rollerworks/breadcrumbs-bundle#3]
> Easy breadcrumbs navigation for Symfony powered applications (Not the Symfony FrameworkBundle).

What should that tell me? It does not work in the FullStack standard-edition Framework? 
Or is the full stack framework needed? The sentence is somehow very confusing.

**Comment by sstok** [comment]
It means you can use it without installing the Symfony FrameworkBundle. So if you only use the Symfony HttpKernel Bundle architecture you can also this bundle :+1: (with some minor notes of course as the request_stack needs to registered as a service).

You can perfectly use this in a Symfony full stack application :smiley:

**Comment by sstok** [comment]
I updated the README to make this more clean, thanks for the heads-up :+1:

**Comment by mablae** [comment]
Thanks for the clarification AND the awesome bundle. I will try it these days. :heart:
